language: c
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y texlive texlive-lang-polish texlive-latex-recommended texlive-latex-extra
script: make
after_success:
- curl --upload-file ./int.pdf https://transfer.sh/int.pdf
